import type { Metadata } from 'next'
import './globals.css'
import Provider from '@/app/_trpc/Provider'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/ui/app-sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='flex h-screen w-screen overflow-hidden'>
        <Provider>
          <SidebarProvider>
            <AppSidebar />
            <main className='flex-1 overflow-auto p-4'>{children}</main>
          </SidebarProvider>
        </Provider>
      </body>
    </html>
  )
}
