import type { Metadata } from 'next'
import './globals.css'
import Provider from '@/app/_trpc/Provider'
import { SidebarProvider } from '@/components/ui/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Provider>
          <SidebarProvider>
            <main className='flex justify-between min-h-screen bg-slate-500 w-full'>
              {/* <AppSidebar /> */}
              <div className='flex-1 bg-green-500'>{children}</div>
            </main>
          </SidebarProvider>
        </Provider>
      </body>
    </html>
  )
}
